# Filterbank config
filterbank:
  stft_n_filters: 512
  stft_kernel_size: 400
  stft_stride: 100
masknet:
  architecture: DCCRN-CL
data:
  task: enh_single
  train_dir: /home/zzf/dataset/librimix/Libri2Mix/wav8k/min/metadata
  valid_dir: /home/zzf/dataset/librimix/Libri2Mix/wav8k/min/metadata
  sample_rate: 8000 # 16000
  n_src: 1
  segment: 4
training:
  epochs: 200
  batch_size: 12
  num_workers: 4
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: !!float 1e-5
