


dccrn_0325:
	CUDA_VISIBLE_DEVICES=0,1 python train.py --conf "dccrn_0325.yml" --exp_dir "/home/zzf/experiment-asteroid/libri1mix_enhsingle_8k/dccrn_0325"
dccrn_0325_eval:
	CUDA_VISIBLE_DEVICES=0 python eval.py --write_wav True --exp_dir "/home/zzf/experiment-asteroid/libri1mix_enhsingle_8k/dccrn_0325" --result_dir "/home/zzf/experiment-asteroid/libri1mix_enhsingle_8k/dccrn_0325/eval" --csv_dir "/home/zzf/dataset/librimix/Libri2Mix/wav8k/min/metadata/" --task enh_single