


convtasnet_0324:
	rm -rf /home/zzf/experiment-asteroid/libri2mix_sepclean_8k/convtasnet_0324
	CUDA_VISIBLE_DEVICES=2,3 python train.py --conf "convtasnet_0324.yml" --exp_dir "/home/zzf/experiment-asteroid/libri2mix_sepclean_8k/convtasnet_0324"