


convtasnet_0324:
	CUDA_VISIBLE_DEVICES=2,3 python train.py --conf "convtasnet_0324.yml" --exp_dir "/home/zzf/experiment-asteroid/libri2mix_sepclean_8k/convtasnet_0324"
convtasnet_0324_eval:
	CUDA_VISIBLE_DEVICES=2 python eval.py --write_wav True --exp_dir "/home/zzf/experiment-asteroid/libri2mix_sepclean_8k/convtasnet_0324" --result_dir "/home/zzf/experiment-asteroid/libri2mix_sepclean_8k/convtasnet_0324/eval" --csv_dir "/home/zzf/dataset/librimix/Libri2Mix/wav8k/min/metadata/" --task sep_clean